### ISSUE TITLE
Use GH auth mechanism instead of unconditionally requiring `$GITHUB_TOKEN`

### ISSUE THREAD

**Issue by yermulnik** [johnmanjiro13/gh-cmcm#105]
It would be great if this extension didn't require `$GITHUB_TOKEN` by default, but instead utilized auth mechanism of the GH CLI. The https://github.com/cli/go-gh might probably help with this. Thanks.

**Comment by johnmanjiro13** [comment]
Thank you @yermulnik.
I'll do it when I have time.
